### ISSUE TITLE
Detrending tutorial

### ISSUE THREAD

**Issue by bpablo** [phoebe-project/phoebe2-workshop#1] opened 2022-05-13 01:13 UTC
- [ ] plt.style.use('jupyter') - I don't have this style available by default. Either we need to specify a version number for matplotlib (i did an entirely fresh install on May 11th) , tell people where to get this style, or use a more generic one.
- [ ]  can't access the dataset for TIC 91961. When I got to the linked page and click LC under data I get a 404 message. Can we add this to the tutorial repo?

**Comment by aprsa** [comment] 2022-05-13 16:22
Commit #778d697 changes the reference from global mplstyle to local; the file has been added to the toplevel workshop 2022 branch. The dataset is available in the same branch and no change was required there (@bpablo confirmed it). I am closing this issue but feel free to reopen if anything is still acting up.

**Closed as completed by aprsa** 2022-05-13 16:22 UTC

**Comment by kecnry** [comment] 2022-05-13 16:44
Should we link to the file from the notebook directly (or use the same filename that is available if downloading from the TESS catalog)?

**Comment by aprsa** [comment] 2022-05-13 17:06
@kecnry catalog TESS files have a phase column in there that I'd removed from the tutorial data file; we can easily link to it if you think it'll help?

**Comment by kecnry** [comment] 2022-05-13 17:10
Ah, ok, then I think linking to it will be helpful for anyone that chooses to access the tutorials from the website rather than cloning the repo. You should be able to just link to the raw version of the file on GitHub (might bite us next year when we have a new branch, but that sounds like a problem for future us).

**Comment by kecnry** [comment] 2022-05-13 17:12
You'll have the same problem with the mplstyle file... is that necessary to have?

**Comment by aprsa** [comment] 2022-05-13 17:15
It makes plots nicer. My suggestion would be to add to the style file incrementally and use it for a uniform appearance of all our tutorials -- eventually.

**Comment by kecnry** [comment] 2022-05-13 17:21
But the tutorials still have to run if you download a single ipynb file (without cloning the whole repo).  So maybe wrap it in a try/except or check if the file exists first?

**Comment by aprsa** [comment] 2022-05-13 17:23
would it make sense to consider bundling it with phoebe 2.4? Say as part of autofig?

**Comment by kecnry** [comment] 2022-05-13 17:45
I would be hesitant to do that since we'll need to make sure that user customization still overrides (and styling preferences are quite subjective).  If the tutorial works without the file, I would just remove it for now.

**Comment by aprsa** [comment] 2022-05-13 19:19
I'll replace it with explicit style changes to make the plots legible, but I still think that better defaults for jupyter notebooks are needed.

**Comment by aprsa** [comment] 2022-05-14 15:35
Done.
